require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/audit_entries", type: :request do
  # AuditEntry. As you add validations to AuditEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AuditEntry.create! valid_attributes
      get audit_entries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      audit_entry = AuditEntry.create! valid_attributes
      get audit_entry_url(audit_entry)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_audit_entry_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      audit_entry = AuditEntry.create! valid_attributes
      get edit_audit_entry_url(audit_entry)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AuditEntry" do
        expect {
          post audit_entries_url, params: {audit_entry: valid_attributes}
        }.to change(AuditEntry, :count).by(1)
      end

      it "redirects to the created audit_entry" do
        post audit_entries_url, params: {audit_entry: valid_attributes}
        expect(response).to redirect_to(audit_entry_url(AuditEntry.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AuditEntry" do
        expect {
          post audit_entries_url, params: {audit_entry: invalid_attributes}
        }.to change(AuditEntry, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post audit_entries_url, params: {audit_entry: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested audit_entry" do
        audit_entry = AuditEntry.create! valid_attributes
        patch audit_entry_url(audit_entry), params: {audit_entry: new_attributes}
        audit_entry.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the audit_entry" do
        audit_entry = AuditEntry.create! valid_attributes
        patch audit_entry_url(audit_entry), params: {audit_entry: new_attributes}
        audit_entry.reload
        expect(response).to redirect_to(audit_entry_url(audit_entry))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        audit_entry = AuditEntry.create! valid_attributes
        patch audit_entry_url(audit_entry), params: {audit_entry: invalid_attributes}
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested audit_entry" do
      audit_entry = AuditEntry.create! valid_attributes
      expect {
        delete audit_entry_url(audit_entry)
      }.to change(AuditEntry, :count).by(-1)
    end

    it "redirects to the audit_entries list" do
      audit_entry = AuditEntry.create! valid_attributes
      delete audit_entry_url(audit_entry)
      expect(response).to redirect_to(audit_entries_url)
    end
  end
end
